# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Sub-Operable`
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	:runtime-requirement    [ :on "isa"^^:CpanId ];
	:runtime-requirement    [ :on "Exporter::Tiny"^^:CpanId ];
	:runtime-requirement    [ :on "perl 5.008009"^^:CpanId ];
	.

